Warning message:
In read.table("./data/0201.grade.txt", header = FALSE, sep = ",",  :
  incomplete final line found by readTableHeader on './data/0201.grade.txt'
'data.frame':	5 obs. of  4 variables:
 $ V1: chr  "index" "1" "1" "1" ...
 $ V2: Factor w/ 2 levels "Male","Female": NA 1 1 1 1
 $ V3: chr  "subject" "1" "1" "1" ...
 $ V4: chr  "grade" "3" "4" "5" ...

  Male Female 
     4      0 
Error: object 'afaf' not found
Execution halted
