   id  sex  age  job  mrg  school  g_day  age_c  g_day_c   o1  o2  fb1  fb2  \
0  1   1    18   1    2    1       3      1      2        4    4   1    4     
1  2   2    23   5    2    3       3      2      2        3    3   5    2     
2  3   1    23   1    2    3       1      2      1        3    3   2    3     
3  4   2    20   1    2    2       3      1      2        4 4  2   3    4     
4  5   1    22   2    2    4       1      2      1        3    3   3    3     
5  6   1    24   2    2    4       2      2      1        4    4   2    2     
6  7   1    21   5    2    2       1      2      1        3    4   3    3     

   fb3  if1  if2  if3  d1  d2  d3  d4  c1  c2  c3  c4  f1  f2  f3   f4  
0  5    1    2    2    4   5   1   5   4   5   5   4   5   4   2   5.0  
1  5    3    3    3    3   3   3   5   3   3   3   3   3   3   3   3.0  
2  4    4    2    4    3   4   3   2   2   3   3   4   4   4   2   3.0  
3  2    2    3    5    2   5   3   4   4   2   3   2   2   5   1  NaN   
4  3    2    2    2    3   3   3   3   2   3   2   2   3   4   3   2.0  
5  2    2    2    2    3   2   3   2   3   3   3   3   1   3   3   3.0  
6  3    3    3    4    4   3   3   2   3   4   4   4   4   4   3   3.0  
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    afaf
NameError: name 'afaf' is not defined
