Warning message:
In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on './data/0202.grade.csv'
   sex subject grade
1 Male       1     3
2 Male       1     4
3 Male       1     5
4 Male       1     3
'data.frame':	4 obs. of  3 variables:
 $ sex    : Factor w/ 1 level "Male": 1 1 1 1
 $ subject: int  1 1 1 1
 $ grade  : int  3 4 5 3
Error: object 'afaf' not found
Execution halted
