xkbcommon: ERROR: failed to add default include path 
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    # https://raw.githubusercontent.com/youngminpark2559/statistics_analysis/master/Statistical_analysis/SangChulLee_py/005_Probability_distribution/003_Binomial_distribution2/pics/2019_07_13_20:07:46.png
NameError: name 'afaf' is not defined
