xkbcommon: ERROR: failed to add default include path 
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
main.py:82: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  cold_sr[cold_sr==1]="No_cold"
result (0.6971153846153846, 0.9998746450692104, 9, array([[0.89655172, 0.89655172, 0.89655172, 0.89655172, 1.34482759,
        1.34482759, 1.34482759, 1.79310345, 1.79310345, 1.79310345],
       [1.10344828, 1.10344828, 1.10344828, 1.10344828, 1.65517241,
        1.65517241, 1.65517241, 2.20689655, 2.20689655, 2.20689655]]))
Traceback (most recent call last):
  File "main.py", line 306, in <module>
    afaf
NameError: name 'afaf' is not defined
