xkbcommon: ERROR: failed to add default include path 
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
tTestResult Ttest_indResult(statistic=-3.4171504415997087, pvalue=0.004168243859583699)
A_tire_mean 40479.25
A_tire_var 50002639.071428575
A_tire_std 7071.254419933466
B_tire_mean 50920.875
B_tire_var 24693468.69642857
B_tire_std 4969.252327707718
Traceback (most recent call last):
  File "main.py", line 277, in <module>
    afaf
NameError: name 'afaf' is not defined
